//tareas
export const  SELECCIONAR_TAREAS = 'SELECCIONAR_TAREAS';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const VALIDAR_TAREA = 'VALIDAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const MODIFICAR_TAREA = 'MODIFICAR_TAREA';
export const ESTADO_TAREA = 'ESTADO_TAREA';
export const TAREA_A_MODIFICAR = 'TAREA_A_MODIFICAR';

//alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//auth
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

////////////////////////////////////////////////////////////////////

//advice
export const ADD_ADVICE = 'ADD_ADVICE';
export const ADD_ADVICE_SUCCESS = 'ADD_ADVICE_SUCCESS';
export const ADD_ADVICE_ERROR = 'ADD_ADVICE_ERROR';

//list advices
export const START_DOWNLOAD_ADVICES = 'START_DOWNLOAD_ADVICES';
export const DOWNLOAD_ADVICES_SUCCESS = 'DOWNLOAD_ADVICES_SUCCESS';
export const DOWNLOAD_ADVICES_ERROR = 'DOWNLOAD_ADVICES_ERROR';

//advice delete
export const GET_ADVICE_DELETE = 'GET_ADVICE_DELETE';
export const ADVICE_DELETE_SUCCESS = 'ADVICE_DELETE_SUCCESS';
export const ADVICE_DELETE_ERROR = 'ADVICE_DELETE_ERROR';

//advice modify
export const GET_ADVICE_MODIFY = 'GET_ADVICE_MODIFY';
export const ADVICE_MODIFY_SUCCESS = 'ADVICE_MODIFY_SUCCESS';
export const ADVICE_MODIFY_ERROR = 'ADVICE_MODIFY_ERROR';
export const START_MODIFY_ADVICE = 'START_MODIFY_ADVICE';

////////////////////////////////////////////////////////////////////

//list meetings
export const START_DOWNLOAD_MEETINGS = 'START_DOWNLOAD_MEETINGS';
export const DOWNLOAD_MEETINGS_SUCCESS = 'DOWNLOAD_MEETINGS_SUCCESS';
export const DOWNLOAD_MEETINGS_ERROR = 'DOWNLOAD_MEETINGS_ERROR';

//meeting
export const ADD_MEETING = 'ADD_MEETING';
export const ADD_MEETING_SUCCESS = 'ADD_MEETING_SUCCESS';
export const ADD_MEETING_ERROR = 'ADD_MEETING_ERROR';

//MEETING modify
export const GET_MEETING_MODIFY = 'GET_MEETING_MODIFY';
export const MEETING_MODIFY_SUCCESS = 'MEETING_MODIFY_SUCCESS';
export const MEETING_MODIFY_ERROR = 'MEETING_MODIFY_ERROR';
export const START_MODIFY_MEETING = 'START_MODIFY_MEETING';

//MEETING delete
export const GET_MEETING_DELETE = 'GET_MEETING_DELETE';
export const MEETING_DELETE_SUCCESS = 'MEETING_DELETE_SUCCESS';
export const MEETING_DELETE_ERROR = 'MEETING_DELETE_ERROR';

////////////////////////////////////////////////////////////////////

//MAPS
export const ADD_LAT = 'ADD_LAT';
export const ADD_LNG = 'ADD_LNG';
export const ADD_UBICATION = 'ADD_UBICATION';
export const CLEAR = 'CLEAR';

////////////////////////////////////////////////////////////////////

//LIST COUPON
export const DOWNLOAD_COUPONS_SUCCESS = 'DOWNLOAD_COUPONS_SUCCESS';
export const DOWNLOAD_COUPONS_ERROR = 'DOWNLOAD_COUPONS_ERROR';
export const START_DOWNLOAD_COUPONS = 'START_DOWNLOAD_COUPONS';

//COUPON
export const ADD_COUPON = 'ADD_COUPON';
export const ADD_COUPON_SUCCESS = 'ADD_COUPON_SUCCESS';
export const ADD_COUPON_ERROR = 'ADD_COUPON_ERROR';

//COUPON MODIFY
export const GET_COUPON_MODIFY = 'GET_COUPON_MODIFY';
export const COUPON_MODIFY_ERROR = 'COUPON_MODIFY_ERROR';
export const COUPON_MODIFY_SUCCESS = 'COUPON_MODIFY_SUCCESS';

//COUPON DELETE
export const COUPON_DELETE_ERROR = 'COUPON_DELETE_ERROR';
export const GET_COUPON_DELETE = 'GET_COUPON_DELETE';
export const COUPON_DELETE_SUCCESS = 'COUPON_DELETE_SUCCESS';

//COUPON VERIFY
export const COUPON_VERIFY_ERROR = 'COUPON_VERIFY_ERROR';
export const COUPON_VERIFY_SUCCESS = 'COUPON_VERIFY_SUCCESS';





////////////////////////////////////////////////////////////////////

//LIST RECYCLER
export const DOWNLOAD_RECYCLERS_SUCCESS = 'DOWNLOAD_RECYCLERS_SUCCESS';
export const DOWNLOAD_RECYCLERS_ERROR = 'DOWNLOAD_RECYCLERS_ERROR';
export const START_DOWNLOAD_RECYCLERS = 'START_DOWNLOAD_RECYCLERS';

//RECYCLER
export const ADD_RECYCLER = 'ADD_RECYCLER';
export const ADD_RECYCLER_SUCCESS = 'ADD_RECYCLER_SUCCESS';
export const ADD_RECYCLER_ERROR = 'ADD_RECYCLER_ERROR';

//RECYCLER MODIFY
export const GET_RECYCLER_MODIFY = 'GET_RECYCLER_MODIFY';
export const RECYCLER_MODIFY_ERROR = 'RECYCLER_MODIFY_ERROR';
export const RECYCLER_MODIFY_SUCCESS = 'RECYCLER_MODIFY_SUCCESS';

//RECYCLER DELETE
export const RECYCLER_DELETE_ERROR = 'RECYCLER_DELETE_ERROR';
export const GET_RECYCLER_DELETE = 'GET_RECYCLER_DELETE';
export const RECYCLER_DELETE_SUCCESS = 'RECYCLER_DELETE_SUCCESS';

//LIST SERVICES
export const DOWNLOAD_SERVICES_SUCCESS = 'DOWNLOAD_SERVICES_SUCCESS';
export const DOWNLOAD_SERVICES_ERROR = 'DOWNLOAD_SERVICES_ERROR';
export const START_DOWNLOAD_SERVICES = 'START_DOWNLOAD_SERVICES';

//LIST SERVICES PENDINGS
export const START_DOWNLOAD_SERVICES_PENDINGS = 'START_DOWNLOAD_SERVICES_PENDINGS';
export const DOWNLOAD_SERVICES_PENDINGS_SUCCESS = 'DOWNLOAD_SERVICES_PENDINGS_SUCCESS';
export const DOWNLOAD_SERVICES_PENDINGS_ERROR = 'DOWNLOAD_SERVICES_PENDINGS_ERROR';
export const START_MODIFY_SERVICES_PENDINGS = 'START_MODIFY_SERVICES_PENDINGS';
export const SERVICES_PENDINGS_MODIFY_SUCCESS = 'SERVICES_PENDINGS_MODIFY_SUCCESS';
export const SERVICES_PENDINGS_MODIFY_ERROR = 'SERVICES_PENDINGS_MODIFY_ERROR';



