//los types siempre se escriben en mayuscula
export const FORMULARIO_MATERIA = 'FORMULARIO_MATERIA';
export const OBTENER_MATERIAS = 'OBTENER_MATERIAS';
export const AGREGAR_MATERIA = 'AGREGAR_MATERIA';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const MATERIA_ACTUAL = 'MATERIA_ACTUAL';
export const ELIMINAR_MATERIA = 'ELIMINAR_MATERIA';
export const ERROR_MATERIA = 'ERROR_MATERIA';

//tareas
export const  SELECCIONAR_TAREAS = 'SELECCIONAR_TAREAS';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const VALIDAR_TAREA = 'VALIDAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const MODIFICAR_TAREA = 'MODIFICAR_TAREA';
export const ESTADO_TAREA = 'ESTADO_TAREA';
export const TAREA_A_MODIFICAR = 'TAREA_A_MODIFICAR';

//alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//auth
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
